[34기 정진관] Mission 2: 모델링
wecode-bootcamp-korea/34-backend-westagram-3 pull request #7
Opened 2022-06-10 07:49 UTC by dingwan0331

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
- models.py에 User 클래스 생성
- settings.py의 INSTALLED_APPS에 'users' 추가
		 
## 수정 사항들 자세한 내용
- name , email , password , phone_number 를 포함한  User 클래스 생성

## 기타 질문 및 특이 사항
- CharField는 max_length 가 필수 지정옵션으로 알고있는데 name 과 email을 어느정도로 설정해야 하는지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ x ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ x ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ x ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2022-06-10 08:14 UTC, Kang-kyunghun requested changes

2022-06-10 08:14 UTC, Kang-kyunghun commented on students/jingwan/users/models.py
> +    phone_number = models.IntegerField()
- 핸드폰 번호는 숫자의 의미보다는 문자의 의미가 더 강합니다. 이에 맞게 필드를 수정해 주세요.
- 변수명과 class 사이에 공백 추가해 주세요.
- email field에 unique 속성을 추가하셔서 유저가 중복 저장되는 문제가 발생하지 않도록 수정해주세요!(공식 문서에서 그 방법을 찾아보고 적용해주세요.)
- 이름과 관련된 필드는 아래를 참고해서 수정해 주세요.
    - id(계정) → `username`
    - name → `first_name`, `last_name`

2022-06-10 08:48 UTC, Kang-kyunghun requested changes

2022-06-10 08:48 UTC, Kang-kyunghun commented on students/jingwan/users/models.py
> +    phone_number = models.CharField(max_length=20, unique=True)
- username은 붙여서 쓰는 것이 일반적입니다.
- 비밀번호는 다른 유저가 같은 것을 사용할 수도 있기 때문에 unique 속성은 제거해 주세요.

```suggestion
    username    = models.CharField(max_length=30, unique=True)
    first_name   = models.CharField(max_length=161)
    last_name    = models.CharField(max_length=11)
    email        = models.CharField(max_length=254, unique=True)
    password     = models.CharField(max_length=40)
    phone_number = models.CharField(max_length=20)
```

2022-06-10 10:03 UTC, dingwan0331 commented on students/jingwan/users/models.py
> +    phone_number = models.CharField(max_length=20, unique=True)
마지막의 붙은 unique는 핸드폰번호입니다!

2022-06-11 01:19 UTC, Kang-kyunghun commented on students/jingwan/users/models.py
> +    phone_number = models.CharField(max_length=20, unique=True)
그렇군요!! 착각 했습니다.

2022-06-11 01:19 UTC, merged